import type { Project } from "../en/projects";

export const projects: Project[] = [
  {
    slug: "crumbtrail",
    title: "Crumbtrail",
    description: "[Íslensk þýðing kemur hér]",
    url: "https://crumbtrail.valdez.is",
    repo: "https://github.com/benediktvaldez/crumbtrail",
    tags: ["Next.js", "React", "Mantine", "Supabase", "Vercel"],
    featured: true,
    year: 2026,
    type: "personal",
  },
  {
    slug: "fil-rouge-studio",
    title: "Fil Rouge Studio",
    description: "[Íslensk þýðing kemur hér]",
    repo: "https://github.com/benediktvaldez/fil-rouge-studio",
    tags: ["Next.js", "React", "SCSS Modules", "Supabase"],
    featured: true,
    year: 2025,
    type: "personal",
  },
  {
    slug: "olatakjallari",
    title: "Ólátakjallari",
    description: "[Íslensk þýðing kemur hér]",
    repo: "https://github.com/benediktvaldez/olatakjallari",
    tags: ["Next.js", "React", "dnd-kit", "Supabase"],
    featured: true,
    year: 2025,
    type: "personal",
  },
  {
    slug: "svef-voting",
    title: "Kosningakerfi SVEF",
    description: "[Íslensk þýðing kemur hér]",
    tags: ["Next.js", "React", "TypeScript", "GraphQL", "Vitest"],
    featured: true,
    year: "2018 – nú",
    type: "personal",
  },
  {
    slug: "valdez-is",
    title: "valdez.is",
    description: "[Íslensk þýðing kemur hér]",
    repo: "https://github.com/benediktvaldez/web",
    tags: ["Next.js", "React", "CSS Modules", "MDX"],
    featured: false,
    year: 2026,
    type: "personal",
  },
  {
    slug: "jsconf-iceland",
    title: "JSConf Iceland",
    description: "[Íslensk þýðing kemur hér]",
    url: "https://2018.jsconf.is",
    tags: ["Ráðstefna", "Samfélag", "JavaScript"],
    featured: true,
    year: "2016, 2018",
    type: "community",
  },
  {
    slug: "svef",
    title: "Stjórnarmaður SVEF",
    description: "[Íslensk þýðing kemur hér]",
    tags: ["Samfélag", "Viðburðir", "Vefiðnaður"],
    featured: true,
    year: "2015 – 2019",
    type: "community",
  },
];
